version: "3"
services:
  my-web-app-db:
    image: postgres
    environment:
      POSTGRES_DB: "first_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
  my-web-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - my-web-app-db
volumes:
  pgdata:
