CREATE TABLE car
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    number VARCHAR,
    brand  VARCHAR,
    model  VARCHAR,
    color  VARCHAR,
    year   VARCHAR
);

ALTER TABLE car
    OWNER TO postgres;
